name: Push repo to Dataverse

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse 
        uses: actions/checkout@v2
        with:
          DATAVERSE_TOKEN: ${{'secrets.4bbafd57-2547-45f9-8153-3a188bb0de82'}}
          DATAVERSE_SERVER: https://dataverse.pre.csuc.cat
          DATAVERSE_DATASET_DOI: doi:10.80051/data1115
          GITHUB_DIR: READ_CSV/Revisat.ipynb
          DELETE: False
          PUBLISH: FALSE
